version: '3.9'

services:
  app:
    image: imagedoc
    build:
      context: ./
    container_name: 'assignmentApp'
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://database:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  database:
      image: postgres
      ports:
        - "5432:5432"
      environment:
        - POSTGRES_DB=postgres
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
      volumes:
        - database:/var/lib/postgresql/data


volumes:
  database:
    driver: local


