# Build job
build:
  # depends on test's job
  needs: tests
  name: Build
  # Run on Ubuntu using the latest version
  runs-on: ubuntu-latest
  steps:
    # Check-out your repository
    - uses: actions/checkout@v4
    # Set up JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '21'
    # Build the application using Maven
    - name: Build with Maven
      run: mvn -B package -DskipTests --file pom.xml
    # Create staging directory and copy JAR files
    - name: Create staging directory and copy JAR files
      run: |
        mkdir staging
        cp target/*.jar staging
