name: CD - Deploy to Minikube using Github Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  job1:
    name: Build and Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f Dockerfile -t local/imagedoc .
          echo -n "Verifying images: "
          docker images
      - name: Deploy to Minikube
        id: deploy
        run: |
          kubectl apply -f deploy.yaml || echo "kubectl apply failed"
          kubectl wait --for=condition=Ready pod -l app=imagedoc
          kubectl get all
      - name: Check Deployment Status
        if: ${{ steps.deploy.outcome == 'success' }}
        run: |
          kubectl get deployment/demo -o wide
      - name: Check Service Status
        if: ${{ steps.deploy.outcome == 'success' }}
        run: |
          kubectl get service/demo
      - name: Test service URLs
        if: ${{ steps.deploy.outcome == 'success' }}
        run: |
          echo "SERVICE_URL=$(minikube service imagedoc --url)"
          kubectl port-forward service/imagedoc 8080:8080 &> /dev/null &
          sleep 5
          kubectl port-forward service/imagedoc 8080:8080 &> /dev/null &
      - run: |
          curl -i http://localhost:8080/
      - name: Cleanup
        if: ${{ steps.deploy.outcome == 'success' }}
        run: |
          eval $(minikube docker-env -u)
          minikube delete

