name: CD - Deploy to Minikube using Github Actions

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  job1:
    name: Build and Deploy to Minikube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Start Minikube
        id: minikube
        uses: medyagh/setup-minikube@latest
      - name: Try the cluster!
        run: kubectl get pods -A
      - name: Build Image
        run: |
          export SHELL=/bin/bash
          eval $(minikube -p minikube docker-env)
          docker build -f Dockerfile -t local/imagedoc .
          echo -n "Verifying images: "
          docker images
      - name: Deploy to Minikube
        run: |
          kubectl apply -f deploy.yaml
          kubectl get pods --show-labels
          kubectl wait --for=condition=Ready pod -l app=demo --timeout=5m
          kubectl get all
      - name: Echo Service URL
        run: |
          echo "Service URL: $(minikube service demo --url)"
      - name: Test service URLs
        run: |
          minikube service list
          kubectl port-forward service/demo 8080:8080 &> /dev/null &
          sleep 5
      - run: |
          curl -i http://localhost:8080/
      - name: Cleanup
        run: |
          eval $(minikube docker-env -u)
          minikube delete
