name: CI

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Run Tests
        run: mvn -B test

  build:
    needs: tests
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven
        run: mvn -B package -DskipTests --file pom.xml

      - name: List target directory contents
        run: ls -l target

      - name: Check SHA-256 checksum of the JAR file
        run: sha256sum target/demo-0.0.1-SNAPSHOT.jar

      - name: Create staging directory and copy JAR files
        run: |
          mkdir staging
          cp target/*.jar staging

      - name: List staging directory contents
        run: ls -l staging

      - name: Check SHA-256 checksum of the staged JAR file
        run: sha256sum staging/demo-0.0.1-SNAPSHOT.jar

      - name: Commit and push JAR file
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout -b add-jar
          cp staging/demo-0.0.1-SNAPSHOT.jar .
          git add demo-0.0.1-SNAPSHOT.jar
          git commit -m 'Add JAR file'
          git push origin add-jar
