name: CI

on:
  # Manually trigger workflow runs
  workflow_dispatch:
    # Trigger the workflow on push from the main branch
    branches:
      - main

jobs:
  # Test's job
  tests:
    name: Unit tests
    # Run on Ubuntu using the latest version
    runs-on: ubuntu-latest

    steps:
      # Check-out your repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up JDK 21
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      # Run Tests
      - name: Run Tests
        run: mvn -B test
